# Generated by Django 5.2.3 on 2025-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.TextField(),
        ),
    ]
